// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.ActionNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActionPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "execute_now")]
        #pragma warning disable CS1591
        Execute_now,
        #pragma warning restore CS1591
    }
}
