// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.Properties
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PropertiesGetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customOrderSupported property</summary>
        public bool? CustomOrderSupported { get; set; }
        /// <summary>The iterationCount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.Properties.PropertiesGetResponse_iterationCount? IterationCount { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.Properties.PropertiesGetResponse_iterationCount IterationCount { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.Properties.PropertiesGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.Properties.PropertiesGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.Properties.PropertiesGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customOrderSupported", n => { CustomOrderSupported = n.GetBoolValue(); } },
                { "iterationCount", n => { IterationCount = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.Properties.PropertiesGetResponse_iterationCount>(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.Properties.PropertiesGetResponse_iterationCount.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("customOrderSupported", CustomOrderSupported);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.Properties.PropertiesGetResponse_iterationCount>("iterationCount", IterationCount);
        }
    }
}
#pragma warning restore CS0618
