// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Timers.Properties
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertiesGetResponse_supportedPreActions
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "fan_speed_control")]
        #pragma warning disable CS1591
        Fan_speed_control,
        #pragma warning restore CS1591
        [EnumMember(Value = "water_usage_control")]
        #pragma warning disable CS1591
        Water_usage_control,
        #pragma warning restore CS1591
        [EnumMember(Value = "operation_mode_control")]
        #pragma warning disable CS1591
        Operation_mode_control,
        #pragma warning restore CS1591
    }
}
