// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Timers.Properties
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertiesGetResponse_supportedActions
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "full_cleanup")]
        #pragma warning disable CS1591
        Full_cleanup,
        #pragma warning restore CS1591
        [EnumMember(Value = "segment_cleanup")]
        #pragma warning disable CS1591
        Segment_cleanup,
        #pragma warning restore CS1591
    }
}
