// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MapSegmentationCapabilityPutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.MapSegmentationCapabilityPutRequestBody_action? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether or not Segments should be cleaned in order of ID appearance in the Array. Defaults to false. (Needs firmware support)</summary>
        public bool? CustomOrder { get; set; }
        /// <summary>The iteration value applies to all specified Segment IDs. Defaults to 1.</summary>
        public double? Iterations { get; set; }
        /// <summary>The segment_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SegmentIds { get; set; }
#nullable restore
#else
        public List<string> SegmentIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.MapSegmentationCapabilityPutRequestBody"/> and sets the default values.
        /// </summary>
        public MapSegmentationCapabilityPutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.MapSegmentationCapabilityPutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.MapSegmentationCapabilityPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.MapSegmentationCapabilityPutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.MapSegmentationCapabilityPutRequestBody_action>(); } },
                { "customOrder", n => { CustomOrder = n.GetBoolValue(); } },
                { "iterations", n => { Iterations = n.GetDoubleValue(); } },
                { "segment_ids", n => { SegmentIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability.MapSegmentationCapabilityPutRequestBody_action>("action", Action);
            writer.WriteBoolValue("customOrder", CustomOrder);
            writer.WriteDoubleValue("iterations", Iterations);
            writer.WriteCollectionOfPrimitiveValues<string>("segment_ids", SegmentIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
