// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentationCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MapSegmentationCapabilityPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "start_segment_action")]
        #pragma warning disable CS1591
        Start_segment_action,
        #pragma warning restore CS1591
    }
}
