// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.Properties;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\robot\capabilities\WifiConfigurationCapability
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WifiConfigurationCapabilityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The properties property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.Properties.PropertiesRequestBuilder Properties
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.Properties.PropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WifiConfigurationCapabilityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/robot/capabilities/WifiConfigurationCapability", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WifiConfigurationCapabilityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/robot/capabilities/WifiConfigurationCapability", rawUrl)
        {
        }
        /// <summary>
        /// Get current wireless radio status
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityGetResponse?> GetAsWifiConfigurationCapabilityGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityGetResponse> GetAsWifiConfigurationCapabilityGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityGetResponse>(requestInfo, global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get current wireless radio status
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsWifiConfigurationCapabilityGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityResponse>(requestInfo, global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Set new wireless radio configuration
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PutAsync(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PutAsync(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get current wireless radio status
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Set new wireless radio configuration
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability.WifiConfigurationCapabilityRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WifiConfigurationCapabilityRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WifiConfigurationCapabilityRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
