// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WifiConfigurationCapabilityGetResponse_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "connected")]
        #pragma warning disable CS1591
        Connected,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_connected")]
        #pragma warning disable CS1591
        Not_connected,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
