// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.WifiConfigurationCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WifiConfigurationCapabilityGetResponse_details_frequency
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "2.4ghz")]
        #pragma warning disable CS1591
        TwoFourghz,
        #pragma warning restore CS1591
        [EnumMember(Value = "5ghz")]
        #pragma warning disable CS1591
        Fiveghz,
        #pragma warning restore CS1591
    }
}
