// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.LocateCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LocateCapabilityPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "locate")]
        #pragma warning disable CS1591
        Locate,
        #pragma warning restore CS1591
    }
}
