// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapResetCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MapResetCapabilityPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "reset")]
        #pragma warning disable CS1591
        Reset,
        #pragma warning restore CS1591
    }
}
