// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Customizations;
using NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\valetudo\config
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConfigRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The customizations property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Customizations.CustomizationsRequestBuilder Customizations
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Customizations.CustomizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The interfaces property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.InterfacesRequestBuilder Interfaces
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.InterfacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/valetudo/config", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/valetudo/config", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
