// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Valetudo.ActionNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActionPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "dismissWelcomeDialog")]
        #pragma warning disable CS1591
        DismissWelcomeDialog,
        #pragma warning restore CS1591
        [EnumMember(Value = "restoreDefaultConfiguration")]
        #pragma warning disable CS1591
        RestoreDefaultConfiguration,
        #pragma warning restore CS1591
    }
}
