// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Updater
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdaterPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "check")]
        #pragma warning disable CS1591
        Check,
        #pragma warning restore CS1591
        [EnumMember(Value = "download")]
        #pragma warning disable CS1591
        Download,
        #pragma warning restore CS1591
        [EnumMember(Value = "apply")]
        #pragma warning disable CS1591
        Apply,
        #pragma warning restore CS1591
    }
}
