// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Timers.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TimersPutRequestBody_pre_actions : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The params property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions_params? Params { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions_params Params { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "params", n => { Params = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions_params>(global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions_params.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions_params>("params", Params);
            writer.WriteEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersPutRequestBody_pre_actions_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
