// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Timers.Item
{
    /// <summary>
    /// Everything time-related is in UTC
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimersGetResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>The action property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_action? Action { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_action Action { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Day of WeekSunday = 0, Monday = 1, ... Saturday = 6</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? Dow { get; set; }
#nullable restore
#else
        public List<double?> Dow { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The hour property</summary>
        public double? Hour { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>An optional user-defined label for the timer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The minute property</summary>
        public double? Minute { get; set; }
        /// <summary>Actions to run before the main action (e.g. set fan speed to x)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_pre_actions>? PreActions { get; set; }
#nullable restore
#else
        public List<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_pre_actions> PreActions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse"/> and sets the default values.
        /// </summary>
        public TimersGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_action>(global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_action.CreateFromDiscriminatorValue); } },
                { "dow", n => { Dow = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "hour", n => { Hour = n.GetDoubleValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "minute", n => { Minute = n.GetDoubleValue(); } },
                { "pre_actions", n => { PreActions = n.GetCollectionOfObjectValues<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_pre_actions>(global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_pre_actions.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_action>("action", Action);
            writer.WriteCollectionOfPrimitiveValues<double?>("dow", Dow);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteDoubleValue("hour", Hour);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("label", Label);
            writer.WriteDoubleValue("minute", Minute);
            writer.WriteCollectionOfObjectValues<global::NihFix.Valetudo.HttpClient.Api.V2.Timers.Item.TimersGetResponse_pre_actions>("pre_actions", PreActions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
