// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.State
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StateGetResponse_map : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The entities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Entities { get; set; }
#nullable restore
#else
        public UntypedNode Entities { get; set; }
#endif
        /// <summary>The layers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Layers { get; set; }
#nullable restore
#else
        public UntypedNode Layers { get; set; }
#endif
        /// <summary>The metaData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_metaData? MetaData { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_metaData MetaData { get; set; }
#endif
        /// <summary>The pixelSize property</summary>
        public int? PixelSize { get; set; }
        /// <summary>The size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_size? Size { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_size Size { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map"/> and sets the default values.
        /// </summary>
        public StateGetResponse_map()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entities", n => { Entities = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "layers", n => { Layers = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "metaData", n => { MetaData = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_metaData>(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_metaData.CreateFromDiscriminatorValue); } },
                { "pixelSize", n => { PixelSize = n.GetIntValue(); } },
                { "size", n => { Size = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_size>(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_size.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("entities", Entities);
            writer.WriteObjectValue<UntypedNode>("layers", Layers);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_metaData>("metaData", MetaData);
            writer.WriteIntValue("pixelSize", PixelSize);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.State.StateGetResponse_map_size>("size", Size);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
