// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.PersistentMapControlCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PersistentMapControlCapabilityPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "enable")]
        #pragma warning disable CS1591
        Enable,
        #pragma warning restore CS1591
        [EnumMember(Value = "disable")]
        #pragma warning disable CS1591
        Disable,
        #pragma warning restore CS1591
    }
}
