// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.BasicControlCapability
{
    /// <summary>Robot action to perform</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BasicControlCapabilityPutRequestBody_action
    {
        [EnumMember(Value = "start")]
        #pragma warning disable CS1591
        Start,
        #pragma warning restore CS1591
        [EnumMember(Value = "stop")]
        #pragma warning disable CS1591
        Stop,
        #pragma warning restore CS1591
        [EnumMember(Value = "pause")]
        #pragma warning disable CS1591
        Pause,
        #pragma warning restore CS1591
        [EnumMember(Value = "home")]
        #pragma warning disable CS1591
        Home,
        #pragma warning restore CS1591
    }
}
