// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The pA property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pA? PA { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pA PA { get; set; }
#endif
        /// <summary>The pB property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pB? PB { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pB PB { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points"/> and sets the default values.
        /// </summary>
        public CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pA", n => { PA = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pA>(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pA.CreateFromDiscriminatorValue); } },
                { "pB", n => { PB = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pB>(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pB.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pA>("pA", PA);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability.CombinedVirtualRestrictionsCapabilityPutRequestBody_virtualWalls_points_pB>("pB", PB);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
