// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CombinedVirtualRestrictionsCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CombinedVirtualRestrictionsCapabilityGetResponse_restrictedZones_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "regular")]
        #pragma warning disable CS1591
        Regular,
        #pragma warning restore CS1591
        [EnumMember(Value = "mop")]
        #pragma warning disable CS1591
        Mop,
        #pragma warning restore CS1591
    }
}
