// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.Preset;
using NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.Presets;
using NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.Properties;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\robot\capabilities\FanSpeedControlCapability
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FanSpeedControlCapabilityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The preset property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.Preset.PresetRequestBuilder Preset
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.Preset.PresetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The presets property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.Presets.PresetsRequestBuilder Presets
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.Presets.PresetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The properties property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.Properties.PropertiesRequestBuilder Properties
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.Properties.PropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.FanSpeedControlCapabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FanSpeedControlCapabilityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/robot/capabilities/FanSpeedControlCapability", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.FanSpeedControlCapability.FanSpeedControlCapabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FanSpeedControlCapabilityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/robot/capabilities/FanSpeedControlCapability", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
