// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.ManualControlCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ManualControlCapabilityPutRequestBody_movementCommand
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "forward")]
        #pragma warning disable CS1591
        Forward,
        #pragma warning restore CS1591
        [EnumMember(Value = "backward")]
        #pragma warning disable CS1591
        Backward,
        #pragma warning restore CS1591
        [EnumMember(Value = "rotate_clockwise")]
        #pragma warning disable CS1591
        Rotate_clockwise,
        #pragma warning restore CS1591
        [EnumMember(Value = "rotate_counterclockwise")]
        #pragma warning disable CS1591
        Rotate_counterclockwise,
        #pragma warning restore CS1591
    }
}
