// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Events.Item.Interact
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InteractPutRequestBody_interaction
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ok")]
        #pragma warning disable CS1591
        Ok,
        #pragma warning restore CS1591
        [EnumMember(Value = "yes")]
        #pragma warning disable CS1591
        Yes,
        #pragma warning restore CS1591
        [EnumMember(Value = "no")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
        [EnumMember(Value = "reset")]
        #pragma warning disable CS1591
        Reset,
        #pragma warning restore CS1591
    }
}
