// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NihFix.Valetudo.HttpClient.Api.V2.Networkadvertisement.Config;
using NihFix.Valetudo.HttpClient.Api.V2.Networkadvertisement.Properties;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Networkadvertisement
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\networkadvertisement
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NetworkadvertisementRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The config property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Networkadvertisement.Config.ConfigRequestBuilder Config
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Networkadvertisement.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The properties property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Networkadvertisement.Properties.PropertiesRequestBuilder Properties
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Networkadvertisement.Properties.PropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Networkadvertisement.NetworkadvertisementRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NetworkadvertisementRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/networkadvertisement", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Networkadvertisement.NetworkadvertisementRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NetworkadvertisementRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/networkadvertisement", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
