// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Log.Content;
using NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Log.Level;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Log
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\valetudo\log
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LogRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The content property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Log.Content.ContentRequestBuilder Content
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Log.Content.ContentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The level property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Log.Level.LevelRequestBuilder Level
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Log.Level.LevelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Log.LogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/valetudo/log", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Log.LogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/valetudo/log", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
