// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.SpeakerVolumeControlCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SpeakerVolumeControlCapabilityPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "set_volume")]
        #pragma warning disable CS1591
        Set_volume,
        #pragma warning restore CS1591
    }
}
