// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Http.Auth.Basic
{
    [Obsolete("This class is obsolete. Use BasicGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BasicResponse : global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Http.Auth.Basic.BasicGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Http.Auth.Basic.BasicResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Http.Auth.Basic.BasicResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Http.Auth.Basic.BasicResponse();
        }
    }
}
#pragma warning restore CS0618
