// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.SpeakerTestCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SpeakerTestCapabilityPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "play_test_sound")]
        #pragma warning disable CS1591
        Play_test_sound,
        #pragma warning restore CS1591
    }
}
