// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StatusGetResponse_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "init")]
        #pragma warning disable CS1591
        Init,
        #pragma warning restore CS1591
        [EnumMember(Value = "ready")]
        #pragma warning disable CS1591
        Ready,
        #pragma warning restore CS1591
        [EnumMember(Value = "disconnected")]
        #pragma warning disable CS1591
        Disconnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "lost")]
        #pragma warning disable CS1591
        Lost,
        #pragma warning restore CS1591
        [EnumMember(Value = "alert")]
        #pragma warning disable CS1591
        Alert,
        #pragma warning restore CS1591
    }
}
