// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StatusGetResponse_stats_messages : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The bytes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_bytes? Bytes { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_bytes Bytes { get; set; }
#endif
        /// <summary>The count property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_count? Count { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_count Count { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bytes", n => { Bytes = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_bytes>(global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_bytes.CreateFromDiscriminatorValue); } },
                { "count", n => { Count = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_count>(global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_count.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_bytes>("bytes", Bytes);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats_messages_count>("count", Count);
        }
    }
}
#pragma warning restore CS0618
