// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StatusGetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The state property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_state? State { get; set; }
        /// <summary>The stats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats? Stats { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats Stats { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "state", n => { State = n.GetEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_state>(); } },
                { "stats", n => { Stats = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats>(global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_state>("state", State);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Mqtt.Status.StatusGetResponse_stats>("stats", Stats);
        }
    }
}
#pragma warning restore CS0618
