// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Updater.Config
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ConfigGetResponse_updateProvider
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "github")]
        #pragma warning disable CS1591
        Github,
        #pragma warning restore CS1591
        [EnumMember(Value = "github_nightly")]
        #pragma warning disable CS1591
        Github_nightly,
        #pragma warning restore CS1591
    }
}
