// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CurrentStatisticsCapability : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The metaData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability_metaData? MetaData { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability_metaData MetaData { get; set; }
#endif
        /// <summary>Datetime in ISO8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timestamp { get; set; }
#nullable restore
#else
        public string Timestamp { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability_type? Type { get; set; }
        /// <summary>The value property</summary>
        public double? Value { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability"/> and sets the default values.
        /// </summary>
        public CurrentStatisticsCapability()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "metaData", n => { MetaData = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability_metaData>(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability_metaData.CreateFromDiscriminatorValue); } },
                { "timestamp", n => { Timestamp = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability_type>(); } },
                { "value", n => { Value = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability_metaData>("metaData", MetaData);
            writer.WriteStringValue("timestamp", Timestamp);
            writer.WriteEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability.CurrentStatisticsCapability_type>("type", Type);
            writer.WriteDoubleValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
