// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.CurrentStatisticsCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CurrentStatisticsCapability_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "time")]
        #pragma warning disable CS1591
        Time,
        #pragma warning restore CS1591
        [EnumMember(Value = "area")]
        #pragma warning disable CS1591
        Area,
        #pragma warning restore CS1591
        [EnumMember(Value = "count")]
        #pragma warning disable CS1591
        Count,
        #pragma warning restore CS1591
    }
}
