// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Http;
using NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\valetudo\config\interfaces
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InterfacesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The http property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Http.HttpRequestBuilder Http
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Http.HttpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mqtt property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttRequestBuilder Mqtt
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.InterfacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InterfacesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/valetudo/config/interfaces", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.InterfacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InterfacesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/valetudo/config/interfaces", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
