// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RobotGetResponse_modelDetails_supportedAttachments
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "dustbin")]
        #pragma warning disable CS1591
        Dustbin,
        #pragma warning restore CS1591
        [EnumMember(Value = "watertank")]
        #pragma warning disable CS1591
        Watertank,
        #pragma warning restore CS1591
        [EnumMember(Value = "mop")]
        #pragma warning disable CS1591
        Mop,
        #pragma warning restore CS1591
    }
}
