// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.VoicePackManagementCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VoicePackManagementCapabilityPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "download")]
        #pragma warning disable CS1591
        Download,
        #pragma warning restore CS1591
    }
}
