// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.VoicePackManagementCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VoicePackManagementCapabilityGetResponse_operationStatus_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "idle")]
        #pragma warning disable CS1591
        Idle,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloading")]
        #pragma warning disable CS1591
        Downloading,
        #pragma warning restore CS1591
        [EnumMember(Value = "installing")]
        #pragma warning disable CS1591
        Installing,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
