// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Timers
{
    /// <summary>
    /// These vary depending on the Timer Type.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimersPostRequestBody_action_params : IParsable
    {
        /// <summary>The custom_order property</summary>
        public bool? CustomOrder { get; set; }
        /// <summary>The goto_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GotoId { get; set; }
#nullable restore
#else
        public string GotoId { get; set; }
#endif
        /// <summary>The iterations property</summary>
        public int? Iterations { get; set; }
        /// <summary>The segment_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SegmentIds { get; set; }
#nullable restore
#else
        public List<string> SegmentIds { get; set; }
#endif
        /// <summary>The zone_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ZoneId { get; set; }
#nullable restore
#else
        public string ZoneId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Timers.TimersPostRequestBody_action_params"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Timers.TimersPostRequestBody_action_params CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Timers.TimersPostRequestBody_action_params();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_order", n => { CustomOrder = n.GetBoolValue(); } },
                { "goto_id", n => { GotoId = n.GetStringValue(); } },
                { "iterations", n => { Iterations = n.GetIntValue(); } },
                { "segment_ids", n => { SegmentIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "zone_id", n => { ZoneId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("custom_order", CustomOrder);
            writer.WriteStringValue("goto_id", GotoId);
            writer.WriteIntValue("iterations", Iterations);
            writer.WriteCollectionOfPrimitiveValues<string>("segment_ids", SegmentIds);
            writer.WriteStringValue("zone_id", ZoneId);
        }
    }
}
#pragma warning restore CS0618
