// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MqttGetResponse_optionalExposedCapabilities
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ConsumableMonitoringCapability")]
        #pragma warning disable CS1591
        ConsumableMonitoringCapability,
        #pragma warning restore CS1591
        [EnumMember(Value = "CurrentStatisticsCapability")]
        #pragma warning disable CS1591
        CurrentStatisticsCapability,
        #pragma warning restore CS1591
        [EnumMember(Value = "TotalStatisticsCapability")]
        #pragma warning disable CS1591
        TotalStatisticsCapability,
        #pragma warning restore CS1591
        [EnumMember(Value = "SpeakerVolumeControlCapability")]
        #pragma warning disable CS1591
        SpeakerVolumeControlCapability,
        #pragma warning restore CS1591
        [EnumMember(Value = "KeyLockCapability")]
        #pragma warning disable CS1591
        KeyLockCapability,
        #pragma warning restore CS1591
        [EnumMember(Value = "ObstacleAvoidanceControlCapability")]
        #pragma warning disable CS1591
        ObstacleAvoidanceControlCapability,
        #pragma warning restore CS1591
    }
}
