// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MqttPutRequestBody_interfaces_homeassistant : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The cleanAutoconfOnShutdown property</summary>
        public bool? CleanAutoconfOnShutdown { get; set; }
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttPutRequestBody_interfaces_homeassistant"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttPutRequestBody_interfaces_homeassistant CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttPutRequestBody_interfaces_homeassistant();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cleanAutoconfOnShutdown", n => { CleanAutoconfOnShutdown = n.GetBoolValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("cleanAutoconfOnShutdown", CleanAutoconfOnShutdown);
            writer.WriteBoolValue("enabled", Enabled);
        }
    }
}
#pragma warning restore CS0618
