// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MqttGetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The connection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_connection? Connection { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_connection Connection { get; set; }
#endif
        /// <summary>The customizations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_customizations? Customizations { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_customizations Customizations { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The identity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_identity? Identity { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_identity Identity { get; set; }
#endif
        /// <summary>The interfaces property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_interfaces? Interfaces { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_interfaces Interfaces { get; set; }
#endif
        /// <summary>The optionalExposedCapabilities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_optionalExposedCapabilities?>? OptionalExposedCapabilities { get; set; }
#nullable restore
#else
        public List<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_optionalExposedCapabilities?> OptionalExposedCapabilities { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "connection", n => { Connection = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_connection>(global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_connection.CreateFromDiscriminatorValue); } },
                { "customizations", n => { Customizations = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_customizations>(global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_customizations.CreateFromDiscriminatorValue); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "identity", n => { Identity = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_identity>(global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_identity.CreateFromDiscriminatorValue); } },
                { "interfaces", n => { Interfaces = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_interfaces>(global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_interfaces.CreateFromDiscriminatorValue); } },
                { "optionalExposedCapabilities", n => { OptionalExposedCapabilities = n.GetCollectionOfEnumValues<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_optionalExposedCapabilities>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_connection>("connection", Connection);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_customizations>("customizations", Customizations);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_identity>("identity", Identity);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_interfaces>("interfaces", Interfaces);
            writer.WriteCollectionOfEnumValues<global::NihFix.Valetudo.HttpClient.Api.V2.Valetudo.Config.Interfaces.Mqtt.MqttGetResponse_optionalExposedCapabilities>("optionalExposedCapabilities", OptionalExposedCapabilities);
        }
    }
}
#pragma warning restore CS0618
