// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DoNotDisturbCapabilityPutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The end property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_end? End { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_end End { get; set; }
#endif
        /// <summary>The metaData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_metaData? MetaData { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_metaData MetaData { get; set; }
#endif
        /// <summary>The start property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_start? Start { get; set; }
#nullable restore
#else
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_start Start { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody"/> and sets the default values.
        /// </summary>
        public DoNotDisturbCapabilityPutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "end", n => { End = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_end>(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_end.CreateFromDiscriminatorValue); } },
                { "metaData", n => { MetaData = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_metaData>(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_metaData.CreateFromDiscriminatorValue); } },
                { "start", n => { Start = n.GetObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_start>(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_start.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_end>("end", End);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_metaData>("metaData", MetaData);
            writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.DoNotDisturbCapability.DoNotDisturbCapabilityPutRequestBody_start>("start", Start);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
