// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NihFix.Valetudo.HttpClient.Api.V2.System.Host;
using NihFix.Valetudo.HttpClient.Api.V2.System.Runtime;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.System
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\system
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SystemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The host property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.System.Host.HostRequestBuilder Host
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.System.Host.HostRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runtime property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.System.Runtime.RuntimeRequestBuilder Runtime
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.System.Runtime.RuntimeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.System.SystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/system", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.System.SystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/system", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
