// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.ZoneCleaningCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ZoneCleaningCapabilityPutRequestBody_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "clean")]
        #pragma warning disable CS1591
        Clean,
        #pragma warning restore CS1591
    }
}
