// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MapSegmentEditCapabilityPutRequestBodyMember2_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "split_segment")]
        #pragma warning disable CS1591
        Split_segment,
        #pragma warning restore CS1591
    }
}
