// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.Properties;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\robot\capabilities\MapSegmentEditCapability
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MapSegmentEditCapabilityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The properties property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.Properties.PropertiesRequestBuilder Properties
        {
            get => new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.Properties.PropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MapSegmentEditCapabilityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/robot/capabilities/MapSegmentEditCapability", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MapSegmentEditCapabilityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/robot/capabilities/MapSegmentEditCapability", rawUrl)
        {
        }
        /// <summary>
        /// Edit map segments
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PutAsync(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder.MapSegmentEditCapabilityPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PutAsync(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder.MapSegmentEditCapabilityPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Edit map segments
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder.MapSegmentEditCapabilityPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder.MapSegmentEditCapabilityPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1"/>, <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MapSegmentEditCapabilityPutRequestBody : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1? MapSegmentEditCapabilityPutRequestBodyMember1 { get; set; }
#nullable restore
#else
            public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1 MapSegmentEditCapabilityPutRequestBodyMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember2? MapSegmentEditCapabilityPutRequestBodyMember2 { get; set; }
#nullable restore
#else
            public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember2 MapSegmentEditCapabilityPutRequestBodyMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder.MapSegmentEditCapabilityPutRequestBody"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder.MapSegmentEditCapabilityPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityRequestBuilder.MapSegmentEditCapabilityPutRequestBody();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MapSegmentEditCapabilityPutRequestBodyMember1 = new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MapSegmentEditCapabilityPutRequestBodyMember2 = new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MapSegmentEditCapabilityPutRequestBodyMember1 != null)
                {
                    return MapSegmentEditCapabilityPutRequestBodyMember1.GetFieldDeserializers();
                }
                else if(MapSegmentEditCapabilityPutRequestBodyMember2 != null)
                {
                    return MapSegmentEditCapabilityPutRequestBodyMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(MapSegmentEditCapabilityPutRequestBodyMember1 != null)
                {
                    writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1>(null, MapSegmentEditCapabilityPutRequestBodyMember1);
                }
                else if(MapSegmentEditCapabilityPutRequestBodyMember2 != null)
                {
                    writer.WriteObjectValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember2>(null, MapSegmentEditCapabilityPutRequestBodyMember2);
                }
            }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MapSegmentEditCapabilityRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
