// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability
{
    /// <summary>
    /// join_segments action
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MapSegmentEditCapabilityPutRequestBodyMember1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>The action property</summary>
        public global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1_action? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The segment_a_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SegmentAId { get; set; }
#nullable restore
#else
        public string SegmentAId { get; set; }
#endif
        /// <summary>The segment_b_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SegmentBId { get; set; }
#nullable restore
#else
        public string SegmentBId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1"/> and sets the default values.
        /// </summary>
        public MapSegmentEditCapabilityPutRequestBodyMember1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1_action>(); } },
                { "segment_a_id", n => { SegmentAId = n.GetStringValue(); } },
                { "segment_b_id", n => { SegmentBId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::NihFix.Valetudo.HttpClient.Api.V2.Robot.Capabilities.MapSegmentEditCapability.MapSegmentEditCapabilityPutRequestBodyMember1_action>("action", Action);
            writer.WriteStringValue("segment_a_id", SegmentAId);
            writer.WriteStringValue("segment_b_id", SegmentBId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
